### ISSUE TITLE
Action Bar: Icon Visibility - 4pts

### ISSUE THREAD

**Issue by jakedcolbert** [gordon-cs/appbuilder-pwa#18]
Implement visibility for icons in the action bar. Each icon should only be displayed if the config.js file says so. Be sure to use the android app as your reference. 
- Book collection selector
- Search
- Text Appearance
- Audio

**Comment by Jason-Lopez8** [comment]
Made a pull request here: ( https://github.com/sillsdev/appbuilder-pwa/compare/main...gordon-cs:appbuilder-pwa:Action-Bar-Icon-Visibility?expand=1 )
