### ISSUE TITLE
Text Appearance: Text Size - 4

### ISSUE THREAD

**Issue by jakedcolbert** [gordon-cs/appbuilder-pwa#21]
- Add support for dynamically updating text size

**Comment by chrisvire** [comment]
In mainFeatures, there are two settings for the minimum and maximum text size: text-size-min, text-size-max

**Comment by davidmoore1** [comment]
This is done via a slider that sets a variable in stores.js.  The range for the slider is obtained from text-size-min and text-size-max in the config.js file.  If the entries are not present in the file, then default values of 10 and 60 are used for the range.

**Comment by chrisvire** [comment]
Completed with https://github.com/sillsdev/appbuilder-pwa/pull/115
