### ISSUE TITLE
Navigation: Dropdown Styling - 4pts

### ISSUE THREAD

**Issue by jakedcolbert** [gordon-cs/appbuilder-pwa#3]
- Grid view and list view styling support
	- color
	- text
	- arrangement
	- LTR/RTL

**Comment by chrisvire** [comment]
Here is an example of the book grid view being styles with separate colors by the sub group.

https://drive.google.com/file/d/1aCLJNFHj9oWWIk9vV6QWKXObfblRwOvG/view?usp=share_link

On the Colors page, there is a tab for "Book Colors" and the "Color Name" is the name of the Sub Group of the book.

Colors page:
![Image](https://user-images.githubusercontent.com/517814/198677264-ae7791d6-e2f1-4c03-80f6-0dbfdfb70e5e.png)

Book Sub Group:
![Image](https://user-images.githubusercontent.com/517814/198677416-596a5f19-f435-4d96-b5a9-1edc29405020.png)

In the config.js, there is a "type" = "books" 

```json
        {
          "type": "books",
          "colors": {
            "Pentateuch": "#99D8BF",
            "Historical": "#C5E8DA",
            "PoetryWisdom": "#A6DDC7",
            "MajorProphet": "#8CD3B7",
            "MinorProphet": "#B3E2CF",
            "Gospel": "#C9EADD",
            "Acts": "#A8DEC8",
            "PaulineEpistle": "#BCE5D4",
            "GeneralEpistle": "#9EDAC2",
            "Revelation": "#B3E2CF"
          }
        }
```
