### ISSUE TITLE
Drawer: Features > Menu Items - 2pts

### ISSUE THREAD

**Issue by jakedcolbert** [gordon-cs/appbuilder-pwa#42]
- Add support for links inserted in features > menu items in scripture app builder
	- Rate this App
	- Visit our website
	- Find us on Facebook
	- Send us an email
	- Call us
	- Other

**Comment by chrisvire** [comment]
Icons will be impacted by multiple resolution.

Currently the icons are copied to the main data folder. I will move them to the icons folder.
