### ISSUE TITLE
Navigation: Chapter and Verse Navigation - 4pts

### ISSUE THREAD

**Issue by jakedcolbert** [gordon-cs/appbuilder-pwa#5]
- Add support to enable or disable chapter selection menu visibility after user selects a book
- Add support to enable or disable verse selection menu visibility after user selects a chapter
- Add support to enable or disable chapter selection menu when user interacts with chapter number on the app bar
- Add support to enable or disable chapter number visibility on the app bar

**Comment by Jason-Lopez8** [comment]
On app bar done.

**Comment by Jason-Lopez8** [comment]
Functionality for all 4 done unsure of UI aspect

**Comment by Jason-Lopez8** [comment]
Waiting for Chris on update about a bug with drop-downs

**Comment by chrisvire** [comment]
Oh.... I implemented this in https://github.com/sillsdev/appbuilder-pwa/pull/131
