### ISSUE TITLE
Navigation: Book Navigation - 4pts

### ISSUE THREAD

**Issue by jakedcolbert** [gordon-cs/appbuilder-pwa#50]
- Add support to enable or disable book selection menu
- Add support to enable or disable swiping between books
- Add support for book selection menu to be in either list view or grid view based on Features > Navigation > Book Selection option.

**Comment by Jason-Lopez8** [comment]
Unable to do swiping ( Needs to be implemented )

**Comment by Jason-Lopez8** [comment]
Added support to enable or disable book selection menu

**Comment by Jason-Lopez8** [comment]
Added a bugged  list view that would need help in debugging
