### ISSUE TITLE
Navigation: Swipe Between Chapters - 4pts

### ISSUE THREAD

**Issue by Jason-Lopez8** [gordon-cs/appbuilder-pwa#53]
As a user I would like to swipe between chapters without using the Navbar 

- Can use arrows or Svelte supports swipe

**Comment by chrisvire** [comment]
https://www.npmjs.com/package/svelte-gestures

**Comment by chrisvire** [comment]
I have implemented this with:
* https://github.com/sillsdev/appbuilder-pwa/pull/126
* https://github.com/sillsdev/appbuilder-pwa/pull/127.  
 
I was having an issue with the default pan gesture to the left causing the scrolled text to go further left and having a gutter on the right. I suspected implementing the swipe between chapters would override the default pan gesture, which it did.
